// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v6.33.4
// source: events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope is the wire format for every agent- or handler-emitted event.
// Signature covers the canonical marshaling of SigningInput.
type EventEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmitterPubkey     []byte `protobuf:"bytes,1,opt,name=emitter_pubkey,json=emitterPubkey,proto3" json:"emitter_pubkey,omitempty"`                // Ed25519 public key (32 B)
	Tick              uint64 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`                                                      // simulation tick at emission
	SequencePerLedger uint64 `protobuf:"varint,3,opt,name=sequence_per_ledger,json=sequencePerLedger,proto3" json:"sequence_per_ledger,omitempty"` // emitter's claimed next seq for the destination ledger
	Signature         []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                                             // Ed25519(emitter_priv, canonical(SigningInput))
	EventType         string `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                            // discriminator: "Speak" | "Vote" | ...
	Payload           []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                                                 // canonical marshaling of the typed payload below
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEmitterPubkey() []byte {
	if x != nil {
		return x.EmitterPubkey
	}
	return nil
}

func (x *EventEnvelope) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *EventEnvelope) GetSequencePerLedger() uint64 {
	if x != nil {
		return x.SequencePerLedger
	}
	return 0
}

func (x *EventEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SigningInput is the deterministically-marshaled message whose bytes the
// emitter signs. Kept separate from EventEnvelope so signature verification
// is unambiguous regardless of envelope-field ordering on the wire.
type SigningInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmitterPubkey     []byte `protobuf:"bytes,1,opt,name=emitter_pubkey,json=emitterPubkey,proto3" json:"emitter_pubkey,omitempty"`
	Tick              uint64 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	SequencePerLedger uint64 `protobuf:"varint,3,opt,name=sequence_per_ledger,json=sequencePerLedger,proto3" json:"sequence_per_ledger,omitempty"`
	EventType         string `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload           []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *SigningInput) GetEmitterPubkey() []byte {
	if x != nil {
		return x.EmitterPubkey
	}
	return nil
}

func (x *SigningInput) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *SigningInput) GetSequencePerLedger() uint64 {
	if x != nil {
		return x.SequencePerLedger
	}
	return 0
}

func (x *SigningInput) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SigningInput) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Speak struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Speak) Reset() {
	*x = Speak{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Speak) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speak) ProtoMessage() {}

func (x *Speak) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speak.ProtoReflect.Descriptor instead.
func (*Speak) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *Speak) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Speak) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Vote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option string `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"` // scenario enum, validated at admissibility time
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *Vote) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

type OpenChannelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProposedMembers []string `protobuf:"bytes,1,rep,name=proposed_members,json=proposedMembers,proto3" json:"proposed_members,omitempty"`
}

func (x *OpenChannelReq) Reset() {
	*x = OpenChannelReq{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelReq) ProtoMessage() {}

func (x *OpenChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelReq.ProtoReflect.Descriptor instead.
func (*OpenChannelReq) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *OpenChannelReq) GetProposedMembers() []string {
	if x != nil {
		return x.ProposedMembers
	}
	return nil
}

type CloseChannelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *CloseChannelReq) Reset() {
	*x = CloseChannelReq{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseChannelReq) ProtoMessage() {}

func (x *CloseChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseChannelReq.ProtoReflect.Descriptor instead.
func (*CloseChannelReq) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *CloseChannelReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type RequestCapability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CapId         string `protobuf:"bytes,1,opt,name=cap_id,json=capId,proto3" json:"cap_id,omitempty"`
	Justification string `protobuf:"bytes,2,opt,name=justification,proto3" json:"justification,omitempty"`
}

func (x *RequestCapability) Reset() {
	*x = RequestCapability{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCapability) ProtoMessage() {}

func (x *RequestCapability) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCapability.ProtoReflect.Descriptor instead.
func (*RequestCapability) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *RequestCapability) GetCapId() string {
	if x != nil {
		return x.CapId
	}
	return ""
}

func (x *RequestCapability) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

type DropCapability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CapId string `protobuf:"bytes,1,opt,name=cap_id,json=capId,proto3" json:"cap_id,omitempty"`
}

func (x *DropCapability) Reset() {
	*x = DropCapability{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCapability) ProtoMessage() {}

func (x *DropCapability) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCapability.ProtoReflect.Descriptor instead.
func (*DropCapability) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *DropCapability) GetCapId() string {
	if x != nil {
		return x.CapId
	}
	return ""
}

type Yield struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Yield) Reset() {
	*x = Yield{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yield) ProtoMessage() {}

func (x *Yield) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yield.ProtoReflect.Descriptor instead.
func (*Yield) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *Yield) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeclareIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // emitted only on handler request; commits to L_cog_eli
}

func (x *DeclareIntent) Reset() {
	*x = DeclareIntent{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareIntent) ProtoMessage() {}

func (x *DeclareIntent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareIntent.ProtoReflect.Descriptor instead.
func (*DeclareIntent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *DeclareIntent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// CogIndSnapshot is the per-tick record of an agent's induced bias
// vector θ. Stage A (Step 2) writes the six-element zero vector;
// Step 3 lands real steering values.
type CogIndSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string    `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Theta   []float64 `protobuf:"fixed64,2,rep,packed,name=theta,proto3" json:"theta,omitempty"` // six dials: authority, bandwagon, sycophancy, free_ride, collude, deceive
}

func (x *CogIndSnapshot) Reset() {
	*x = CogIndSnapshot{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CogIndSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CogIndSnapshot) ProtoMessage() {}

func (x *CogIndSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CogIndSnapshot.ProtoReflect.Descriptor instead.
func (*CogIndSnapshot) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *CogIndSnapshot) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CogIndSnapshot) GetTheta() []float64 {
	if x != nil {
		return x.Theta
	}
	return nil
}

// HandlerControlEvent records one Handler RPC call to L_ctrl.
// handler_rpc_name is the RPC method name ("SpawnAgent", "Retune", ...);
// handler_request_bytes is the deterministic canonical marshaling of the
// gRPC request with HandlerAuth.signature cleared.
type HandlerControlEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerRpcName      string `protobuf:"bytes,1,opt,name=handler_rpc_name,json=handlerRpcName,proto3" json:"handler_rpc_name,omitempty"`
	HandlerRequestBytes []byte `protobuf:"bytes,2,opt,name=handler_request_bytes,json=handlerRequestBytes,proto3" json:"handler_request_bytes,omitempty"`
	EffectiveTick       uint64 `protobuf:"varint,3,opt,name=effective_tick,json=effectiveTick,proto3" json:"effective_tick,omitempty"` // the tick at which the mutation took effect
}

func (x *HandlerControlEvent) Reset() {
	*x = HandlerControlEvent{}
	mi := &file_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerControlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerControlEvent) ProtoMessage() {}

func (x *HandlerControlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerControlEvent.ProtoReflect.Descriptor instead.
func (*HandlerControlEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{11}
}

func (x *HandlerControlEvent) GetHandlerRpcName() string {
	if x != nil {
		return x.HandlerRpcName
	}
	return ""
}

func (x *HandlerControlEvent) GetHandlerRequestBytes() []byte {
	if x != nil {
		return x.HandlerRequestBytes
	}
	return nil
}

func (x *HandlerControlEvent) GetEffectiveTick() uint64 {
	if x != nil {
		return x.EffectiveTick
	}
	return 0
}

// TickTimeoutIncident records a missed agent emission. Committed to
// L_ctrl alongside the matching Yield_Kernel_Synthesized on L_pub.
type TickTimeoutIncident struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId     string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tick        uint64 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	BudgetNanos uint64 `protobuf:"varint,3,opt,name=budget_nanos,json=budgetNanos,proto3" json:"budget_nanos,omitempty"`
}

func (x *TickTimeoutIncident) Reset() {
	*x = TickTimeoutIncident{}
	mi := &file_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickTimeoutIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickTimeoutIncident) ProtoMessage() {}

func (x *TickTimeoutIncident) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickTimeoutIncident.ProtoReflect.Descriptor instead.
func (*TickTimeoutIncident) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{12}
}

func (x *TickTimeoutIncident) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TickTimeoutIncident) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickTimeoutIncident) GetBudgetNanos() uint64 {
	if x != nil {
		return x.BudgetNanos
	}
	return 0
}

// -- Step 4 elicitation + render-side bookkeeping ------------------------
//
// ElicitationRequest is the kernel's prompt to one agent at one tick,
// asking it to describe the reasoning behind its just-committed action.
// Committed to L_ctrl when triggered (so the trace is auditable from
// the researcher side) and surfaced to the agent via the next
// Subscribe-stream View — see view.proto's optional elicit_request
// field. The agent responds with a DeclareIntent envelope which
// commits to L_cog_eli.
//
// The brief locks K_elicit = 3 (configurable per scenario in YAML).
type ElicitationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId               string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tick                  uint64 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	ActionEventType       string `protobuf:"bytes,3,opt,name=action_event_type,json=actionEventType,proto3" json:"action_event_type,omitempty"`                      // the action just committed (Speak / Vote / Yield / ...)
	ActionSummary         string `protobuf:"bytes,4,opt,name=action_summary,json=actionSummary,proto3" json:"action_summary,omitempty"`                              // kernel-rendered short string used in the elicit user message
	ActionGlobalCommitSeq uint64 `protobuf:"varint,5,opt,name=action_global_commit_seq,json=actionGlobalCommitSeq,proto3" json:"action_global_commit_seq,omitempty"` // global_commit_seq of the action this elicit references
}

func (x *ElicitationRequest) Reset() {
	*x = ElicitationRequest{}
	mi := &file_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElicitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElicitationRequest) ProtoMessage() {}

func (x *ElicitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElicitationRequest.ProtoReflect.Descriptor instead.
func (*ElicitationRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{13}
}

func (x *ElicitationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ElicitationRequest) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *ElicitationRequest) GetActionEventType() string {
	if x != nil {
		return x.ActionEventType
	}
	return ""
}

func (x *ElicitationRequest) GetActionSummary() string {
	if x != nil {
		return x.ActionSummary
	}
	return ""
}

func (x *ElicitationRequest) GetActionGlobalCommitSeq() uint64 {
	if x != nil {
		return x.ActionGlobalCommitSeq
	}
	return 0
}

// ContextTruncation records when the Python L2 renderer dropped
// channel-history messages to fit the per-scenario token budget. The
// drop-oldest policy is the Stage A choice (brief judgment call 3).
// Committed to L_ctrl per agent per tick per truncated channel.
type ContextTruncation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId      string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tick         uint64 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	ChannelId    string `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	DroppedCount uint32 `protobuf:"varint,4,opt,name=dropped_count,json=droppedCount,proto3" json:"dropped_count,omitempty"`
	KeptCount    uint32 `protobuf:"varint,5,opt,name=kept_count,json=keptCount,proto3" json:"kept_count,omitempty"`
}

func (x *ContextTruncation) Reset() {
	*x = ContextTruncation{}
	mi := &file_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextTruncation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextTruncation) ProtoMessage() {}

func (x *ContextTruncation) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextTruncation.ProtoReflect.Descriptor instead.
func (*ContextTruncation) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{14}
}

func (x *ContextTruncation) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ContextTruncation) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *ContextTruncation) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ContextTruncation) GetDroppedCount() uint32 {
	if x != nil {
		return x.DroppedCount
	}
	return 0
}

func (x *ContextTruncation) GetKeptCount() uint32 {
	if x != nil {
		return x.KeptCount
	}
	return 0
}

// MalformedSubmission is the kernel-side record of a Python-adapter-
// collapsed forward-pass output: the model produced something
// unparseable/inadmissible, the adapter replaced it with
// Yield(reason="malformed_output"), and the raw bytes land here for
// later analysis. Step 5's BBI computation conditions on this rate.
// failure ∈ { "parse_error" | "schema_mismatch" | "inadmissible" | "token_limit" | "other" }
type MalformedSubmission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId   string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tick      uint64 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	RawOutput []byte `protobuf:"bytes,3,opt,name=raw_output,json=rawOutput,proto3" json:"raw_output,omitempty"`
	Failure   string `protobuf:"bytes,4,opt,name=failure,proto3" json:"failure,omitempty"`
}

func (x *MalformedSubmission) Reset() {
	*x = MalformedSubmission{}
	mi := &file_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MalformedSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MalformedSubmission) ProtoMessage() {}

func (x *MalformedSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MalformedSubmission.ProtoReflect.Descriptor instead.
func (*MalformedSubmission) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{15}
}

func (x *MalformedSubmission) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MalformedSubmission) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *MalformedSubmission) GetRawOutput() []byte {
	if x != nil {
		return x.RawOutput
	}
	return nil
}

func (x *MalformedSubmission) GetFailure() string {
	if x != nil {
		return x.Failure
	}
	return ""
}

var File_events_proto protoreflect.FileDescriptor

var file_events_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x62, 0x79, 0x7a, 0x6d, 0x69, 0x6e, 0x64, 0x73, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x22, 0xd1, 0x01, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x5f,
	0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x12,
	0x2e, 0x0a, 0x13, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x72, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x65, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69,
	0x63, 0x6b, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x70,
	0x65, 0x72, 0x5f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x11, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x40, 0x0a, 0x05, 0x53,
	0x70, 0x65, 0x61, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x1e, 0x0a,
	0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a,
	0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x30, 0x0a, 0x0f, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x11,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x61, 0x70, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6a, 0x75, 0x73, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27,
	0x0a, 0x0e, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x61, 0x70, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x05, 0x59, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0d, 0x44, 0x65, 0x63, 0x6c,
	0x61, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x0e, 0x43, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x05, 0x74, 0x68, 0x65, 0x74, 0x61, 0x22, 0x9a, 0x01, 0x0a, 0x13, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x28,
	0x0a, 0x10, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x52, 0x70, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x22, 0x67, 0x0a, 0x13, 0x54, 0x69, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x75, 0x64,
	0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x22, 0xcf, 0x01, 0x0a,
	0x12, 0x45, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69,
	0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x37, 0x0a, 0x18, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x73, 0x65,
	0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x15, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x53, 0x65, 0x71, 0x22, 0xa5,
	0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x54, 0x72, 0x75, 0x6e, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74,
	0x69, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x72, 0x6f, 0x70, 0x70,
	0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x65, 0x70, 0x74, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6b, 0x65, 0x70,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7d, 0x0a, 0x13, 0x4d, 0x61, 0x6c, 0x66, 0x6f, 0x72,
	0x6d, 0x65, 0x64, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x61, 0x77, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x72, 0x61, 0x77, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x79, 0x7a, 0x6d, 0x69, 0x6e, 0x64, 0x73, 0x2f, 0x62, 0x79, 0x7a,
	0x6d, 0x69, 0x6e, 0x64, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x76, 0x31, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData = file_events_proto_rawDesc
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_proto_rawDescData)
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_events_proto_goTypes = []any{
	(*EventEnvelope)(nil),       // 0: byzminds.events.v1.EventEnvelope
	(*SigningInput)(nil),        // 1: byzminds.events.v1.SigningInput
	(*Speak)(nil),               // 2: byzminds.events.v1.Speak
	(*Vote)(nil),                // 3: byzminds.events.v1.Vote
	(*OpenChannelReq)(nil),      // 4: byzminds.events.v1.OpenChannelReq
	(*CloseChannelReq)(nil),     // 5: byzminds.events.v1.CloseChannelReq
	(*RequestCapability)(nil),   // 6: byzminds.events.v1.RequestCapability
	(*DropCapability)(nil),      // 7: byzminds.events.v1.DropCapability
	(*Yield)(nil),               // 8: byzminds.events.v1.Yield
	(*DeclareIntent)(nil),       // 9: byzminds.events.v1.DeclareIntent
	(*CogIndSnapshot)(nil),      // 10: byzminds.events.v1.CogIndSnapshot
	(*HandlerControlEvent)(nil), // 11: byzminds.events.v1.HandlerControlEvent
	(*TickTimeoutIncident)(nil), // 12: byzminds.events.v1.TickTimeoutIncident
	(*ElicitationRequest)(nil),  // 13: byzminds.events.v1.ElicitationRequest
	(*ContextTruncation)(nil),   // 14: byzminds.events.v1.ContextTruncation
	(*MalformedSubmission)(nil), // 15: byzminds.events.v1.MalformedSubmission
}
var file_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_rawDesc = nil
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
