// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: handler.proto

package handlerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Handler_SpawnAgent_FullMethodName            = "/byzminds.handler.v1.Handler/SpawnAgent"
	Handler_KillAgent_FullMethodName             = "/byzminds.handler.v1.Handler/KillAgent"
	Handler_Retune_FullMethodName                = "/byzminds.handler.v1.Handler/Retune"
	Handler_OpenChannel_FullMethodName           = "/byzminds.handler.v1.Handler/OpenChannel"
	Handler_CloseChannel_FullMethodName          = "/byzminds.handler.v1.Handler/CloseChannel"
	Handler_AssignTask_FullMethodName            = "/byzminds.handler.v1.Handler/AssignTask"
	Handler_InjectExternalMessage_FullMethodName = "/byzminds.handler.v1.Handler/InjectExternalMessage"
	Handler_Pause_FullMethodName                 = "/byzminds.handler.v1.Handler/Pause"
	Handler_Resume_FullMethodName                = "/byzminds.handler.v1.Handler/Resume"
	Handler_Step_FullMethodName                  = "/byzminds.handler.v1.Handler/Step"
)

// HandlerClient is the client API for Handler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Handler is the researcher's privileged control surface. Every RPC:
//  1. Authenticates the caller against the kernel-known researcher
//     pubkey (per HandlerAuth below).
//  2. Commits an event to L_ctrl recording the RPC name + arguments.
//  3. Mutates kernel state synchronously (channel mint, agent roster,
//     capability table, scheduler pause/step) — wholly within the
//     scheduler's tick boundary so replay is bit-deterministic.
//  4. Returns an Ack pinning the L_ctrl commit metadata.
//
// Stage A doesn't exercise every RPC during baseline runs; we wire them
// now so Step 2+ scenarios and Step 3+ steering don't need a retrofit.
type HandlerClient interface {
	SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error)
	KillAgent(ctx context.Context, in *KillAgentRequest, opts ...grpc.CallOption) (*HandlerAck, error)
	Retune(ctx context.Context, in *RetuneRequest, opts ...grpc.CallOption) (*HandlerAck, error)
	OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error)
	CloseChannel(ctx context.Context, in *CloseChannelRequest, opts ...grpc.CallOption) (*HandlerAck, error)
	AssignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*HandlerAck, error)
	InjectExternalMessage(ctx context.Context, in *InjectExternalMessageRequest, opts ...grpc.CallOption) (*HandlerAck, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*HandlerAck, error)
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*HandlerAck, error)
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*HandlerAck, error)
}

type handlerClient struct {
	cc grpc.ClientConnInterface
}

func NewHandlerClient(cc grpc.ClientConnInterface) HandlerClient {
	return &handlerClient{cc}
}

func (c *handlerClient) SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnAgentResponse)
	err := c.cc.Invoke(ctx, Handler_SpawnAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) KillAgent(ctx context.Context, in *KillAgentRequest, opts ...grpc.CallOption) (*HandlerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerAck)
	err := c.cc.Invoke(ctx, Handler_KillAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) Retune(ctx context.Context, in *RetuneRequest, opts ...grpc.CallOption) (*HandlerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerAck)
	err := c.cc.Invoke(ctx, Handler_Retune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenChannelResponse)
	err := c.cc.Invoke(ctx, Handler_OpenChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) CloseChannel(ctx context.Context, in *CloseChannelRequest, opts ...grpc.CallOption) (*HandlerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerAck)
	err := c.cc.Invoke(ctx, Handler_CloseChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) AssignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*HandlerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerAck)
	err := c.cc.Invoke(ctx, Handler_AssignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) InjectExternalMessage(ctx context.Context, in *InjectExternalMessageRequest, opts ...grpc.CallOption) (*HandlerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerAck)
	err := c.cc.Invoke(ctx, Handler_InjectExternalMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*HandlerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerAck)
	err := c.cc.Invoke(ctx, Handler_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*HandlerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerAck)
	err := c.cc.Invoke(ctx, Handler_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*HandlerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerAck)
	err := c.cc.Invoke(ctx, Handler_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandlerServer is the server API for Handler service.
// All implementations must embed UnimplementedHandlerServer
// for forward compatibility.
//
// Handler is the researcher's privileged control surface. Every RPC:
//  1. Authenticates the caller against the kernel-known researcher
//     pubkey (per HandlerAuth below).
//  2. Commits an event to L_ctrl recording the RPC name + arguments.
//  3. Mutates kernel state synchronously (channel mint, agent roster,
//     capability table, scheduler pause/step) — wholly within the
//     scheduler's tick boundary so replay is bit-deterministic.
//  4. Returns an Ack pinning the L_ctrl commit metadata.
//
// Stage A doesn't exercise every RPC during baseline runs; we wire them
// now so Step 2+ scenarios and Step 3+ steering don't need a retrofit.
type HandlerServer interface {
	SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error)
	KillAgent(context.Context, *KillAgentRequest) (*HandlerAck, error)
	Retune(context.Context, *RetuneRequest) (*HandlerAck, error)
	OpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error)
	CloseChannel(context.Context, *CloseChannelRequest) (*HandlerAck, error)
	AssignTask(context.Context, *AssignTaskRequest) (*HandlerAck, error)
	InjectExternalMessage(context.Context, *InjectExternalMessageRequest) (*HandlerAck, error)
	Pause(context.Context, *PauseRequest) (*HandlerAck, error)
	Resume(context.Context, *ResumeRequest) (*HandlerAck, error)
	Step(context.Context, *StepRequest) (*HandlerAck, error)
	mustEmbedUnimplementedHandlerServer()
}

// UnimplementedHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandlerServer struct{}

func (UnimplementedHandlerServer) SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpawnAgent not implemented")
}
func (UnimplementedHandlerServer) KillAgent(context.Context, *KillAgentRequest) (*HandlerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillAgent not implemented")
}
func (UnimplementedHandlerServer) Retune(context.Context, *RetuneRequest) (*HandlerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retune not implemented")
}
func (UnimplementedHandlerServer) OpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChannel not implemented")
}
func (UnimplementedHandlerServer) CloseChannel(context.Context, *CloseChannelRequest) (*HandlerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseChannel not implemented")
}
func (UnimplementedHandlerServer) AssignTask(context.Context, *AssignTaskRequest) (*HandlerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTask not implemented")
}
func (UnimplementedHandlerServer) InjectExternalMessage(context.Context, *InjectExternalMessageRequest) (*HandlerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectExternalMessage not implemented")
}
func (UnimplementedHandlerServer) Pause(context.Context, *PauseRequest) (*HandlerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedHandlerServer) Resume(context.Context, *ResumeRequest) (*HandlerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedHandlerServer) Step(context.Context, *StepRequest) (*HandlerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedHandlerServer) mustEmbedUnimplementedHandlerServer() {}
func (UnimplementedHandlerServer) testEmbeddedByValue()                 {}

// UnsafeHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandlerServer will
// result in compilation errors.
type UnsafeHandlerServer interface {
	mustEmbedUnimplementedHandlerServer()
}

func RegisterHandlerServer(s grpc.ServiceRegistrar, srv HandlerServer) {
	// If the following call pancis, it indicates UnimplementedHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Handler_ServiceDesc, srv)
}

func _Handler_SpawnAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).SpawnAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_SpawnAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).SpawnAgent(ctx, req.(*SpawnAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_KillAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).KillAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_KillAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).KillAgent(ctx, req.(*KillAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_Retune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetuneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).Retune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_Retune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).Retune(ctx, req.(*RetuneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_OpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).OpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_OpenChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).OpenChannel(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_CloseChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).CloseChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_CloseChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).CloseChannel(ctx, req.(*CloseChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_AssignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).AssignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_AssignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).AssignTask(ctx, req.(*AssignTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_InjectExternalMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectExternalMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).InjectExternalMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_InjectExternalMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).InjectExternalMessage(ctx, req.(*InjectExternalMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handler_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Handler_ServiceDesc is the grpc.ServiceDesc for Handler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Handler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "byzminds.handler.v1.Handler",
	HandlerType: (*HandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpawnAgent",
			Handler:    _Handler_SpawnAgent_Handler,
		},
		{
			MethodName: "KillAgent",
			Handler:    _Handler_KillAgent_Handler,
		},
		{
			MethodName: "Retune",
			Handler:    _Handler_Retune_Handler,
		},
		{
			MethodName: "OpenChannel",
			Handler:    _Handler_OpenChannel_Handler,
		},
		{
			MethodName: "CloseChannel",
			Handler:    _Handler_CloseChannel_Handler,
		},
		{
			MethodName: "AssignTask",
			Handler:    _Handler_AssignTask_Handler,
		},
		{
			MethodName: "InjectExternalMessage",
			Handler:    _Handler_InjectExternalMessage_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _Handler_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Handler_Resume_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _Handler_Step_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handler.proto",
}
