// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: kernel.proto

package kernelv1

import (
	context "context"
	eventsv1 "github.com/byzminds/byzminds/proto/eventsv1"
	viewv1 "github.com/byzminds/byzminds/proto/viewv1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kernel_SubmitEvent_FullMethodName = "/byzminds.kernel.v1.Kernel/SubmitEvent"
	Kernel_GetView_FullMethodName     = "/byzminds.kernel.v1.Kernel/GetView"
	Kernel_Subscribe_FullMethodName   = "/byzminds.kernel.v1.Kernel/Subscribe"
)

// KernelClient is the client API for Kernel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Kernel is the gRPC surface of the deterministic core.
//
// SubmitEvent and GetView are Step 1 surface (committed-event admission +
// researcher snapshot reads). Subscribe is Step 2 surface: a live
// per-tick stream of BuildView outputs for one registered agent.
type KernelClient interface {
	SubmitEvent(ctx context.Context, in *eventsv1.EventEnvelope, opts ...grpc.CallOption) (*CommitReceipt, error)
	GetView(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventView], error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[viewv1.View], error)
}

type kernelClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelClient(cc grpc.ClientConnInterface) KernelClient {
	return &kernelClient{cc}
}

func (c *kernelClient) SubmitEvent(ctx context.Context, in *eventsv1.EventEnvelope, opts ...grpc.CallOption) (*CommitReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitReceipt)
	err := c.cc.Invoke(ctx, Kernel_SubmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelClient) GetView(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventView], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kernel_ServiceDesc.Streams[0], Kernel_GetView_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ViewRequest, EventView]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kernel_GetViewClient = grpc.ServerStreamingClient[EventView]

func (c *kernelClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[viewv1.View], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kernel_ServiceDesc.Streams[1], Kernel_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, viewv1.View]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kernel_SubscribeClient = grpc.ServerStreamingClient[viewv1.View]

// KernelServer is the server API for Kernel service.
// All implementations must embed UnimplementedKernelServer
// for forward compatibility.
//
// Kernel is the gRPC surface of the deterministic core.
//
// SubmitEvent and GetView are Step 1 surface (committed-event admission +
// researcher snapshot reads). Subscribe is Step 2 surface: a live
// per-tick stream of BuildView outputs for one registered agent.
type KernelServer interface {
	SubmitEvent(context.Context, *eventsv1.EventEnvelope) (*CommitReceipt, error)
	GetView(*ViewRequest, grpc.ServerStreamingServer[EventView]) error
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[viewv1.View]) error
	mustEmbedUnimplementedKernelServer()
}

// UnimplementedKernelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelServer struct{}

func (UnimplementedKernelServer) SubmitEvent(context.Context, *eventsv1.EventEnvelope) (*CommitReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEvent not implemented")
}
func (UnimplementedKernelServer) GetView(*ViewRequest, grpc.ServerStreamingServer[EventView]) error {
	return status.Errorf(codes.Unimplemented, "method GetView not implemented")
}
func (UnimplementedKernelServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[viewv1.View]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedKernelServer) mustEmbedUnimplementedKernelServer() {}
func (UnimplementedKernelServer) testEmbeddedByValue()                {}

// UnsafeKernelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelServer will
// result in compilation errors.
type UnsafeKernelServer interface {
	mustEmbedUnimplementedKernelServer()
}

func RegisterKernelServer(s grpc.ServiceRegistrar, srv KernelServer) {
	// If the following call pancis, it indicates UnimplementedKernelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kernel_ServiceDesc, srv)
}

func _Kernel_SubmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(eventsv1.EventEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).SubmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kernel_SubmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).SubmitEvent(ctx, req.(*eventsv1.EventEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kernel_GetView_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ViewRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServer).GetView(m, &grpc.GenericServerStream[ViewRequest, EventView]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kernel_GetViewServer = grpc.ServerStreamingServer[EventView]

func _Kernel_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, viewv1.View]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kernel_SubscribeServer = grpc.ServerStreamingServer[viewv1.View]

// Kernel_ServiceDesc is the grpc.ServiceDesc for Kernel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kernel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "byzminds.kernel.v1.Kernel",
	HandlerType: (*KernelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEvent",
			Handler:    _Kernel_SubmitEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetView",
			Handler:       _Kernel_GetView_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Kernel_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kernel.proto",
}
