# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from byzminds_agent.proto_gen import handler_pb2 as handler__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in handler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HandlerStub(object):
    """Handler is the researcher's privileged control surface. Every RPC:
    1. Authenticates the caller against the kernel-known researcher
    pubkey (per HandlerAuth below).
    2. Commits an event to L_ctrl recording the RPC name + arguments.
    3. Mutates kernel state synchronously (channel mint, agent roster,
    capability table, scheduler pause/step) — wholly within the
    scheduler's tick boundary so replay is bit-deterministic.
    4. Returns an Ack pinning the L_ctrl commit metadata.

    Stage A doesn't exercise every RPC during baseline runs; we wire them
    now so Step 2+ scenarios and Step 3+ steering don't need a retrofit.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpawnAgent = channel.unary_unary(
                '/byzminds.handler.v1.Handler/SpawnAgent',
                request_serializer=handler__pb2.SpawnAgentRequest.SerializeToString,
                response_deserializer=handler__pb2.SpawnAgentResponse.FromString,
                _registered_method=True)
        self.KillAgent = channel.unary_unary(
                '/byzminds.handler.v1.Handler/KillAgent',
                request_serializer=handler__pb2.KillAgentRequest.SerializeToString,
                response_deserializer=handler__pb2.HandlerAck.FromString,
                _registered_method=True)
        self.Retune = channel.unary_unary(
                '/byzminds.handler.v1.Handler/Retune',
                request_serializer=handler__pb2.RetuneRequest.SerializeToString,
                response_deserializer=handler__pb2.HandlerAck.FromString,
                _registered_method=True)
        self.OpenChannel = channel.unary_unary(
                '/byzminds.handler.v1.Handler/OpenChannel',
                request_serializer=handler__pb2.OpenChannelRequest.SerializeToString,
                response_deserializer=handler__pb2.OpenChannelResponse.FromString,
                _registered_method=True)
        self.CloseChannel = channel.unary_unary(
                '/byzminds.handler.v1.Handler/CloseChannel',
                request_serializer=handler__pb2.CloseChannelRequest.SerializeToString,
                response_deserializer=handler__pb2.HandlerAck.FromString,
                _registered_method=True)
        self.AssignTask = channel.unary_unary(
                '/byzminds.handler.v1.Handler/AssignTask',
                request_serializer=handler__pb2.AssignTaskRequest.SerializeToString,
                response_deserializer=handler__pb2.HandlerAck.FromString,
                _registered_method=True)
        self.InjectExternalMessage = channel.unary_unary(
                '/byzminds.handler.v1.Handler/InjectExternalMessage',
                request_serializer=handler__pb2.InjectExternalMessageRequest.SerializeToString,
                response_deserializer=handler__pb2.HandlerAck.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/byzminds.handler.v1.Handler/Pause',
                request_serializer=handler__pb2.PauseRequest.SerializeToString,
                response_deserializer=handler__pb2.HandlerAck.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/byzminds.handler.v1.Handler/Resume',
                request_serializer=handler__pb2.ResumeRequest.SerializeToString,
                response_deserializer=handler__pb2.HandlerAck.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/byzminds.handler.v1.Handler/Step',
                request_serializer=handler__pb2.StepRequest.SerializeToString,
                response_deserializer=handler__pb2.HandlerAck.FromString,
                _registered_method=True)


class HandlerServicer(object):
    """Handler is the researcher's privileged control surface. Every RPC:
    1. Authenticates the caller against the kernel-known researcher
    pubkey (per HandlerAuth below).
    2. Commits an event to L_ctrl recording the RPC name + arguments.
    3. Mutates kernel state synchronously (channel mint, agent roster,
    capability table, scheduler pause/step) — wholly within the
    scheduler's tick boundary so replay is bit-deterministic.
    4. Returns an Ack pinning the L_ctrl commit metadata.

    Stage A doesn't exercise every RPC during baseline runs; we wire them
    now so Step 2+ scenarios and Step 3+ steering don't need a retrofit.
    """

    def SpawnAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retune(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectExternalMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpawnAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnAgent,
                    request_deserializer=handler__pb2.SpawnAgentRequest.FromString,
                    response_serializer=handler__pb2.SpawnAgentResponse.SerializeToString,
            ),
            'KillAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.KillAgent,
                    request_deserializer=handler__pb2.KillAgentRequest.FromString,
                    response_serializer=handler__pb2.HandlerAck.SerializeToString,
            ),
            'Retune': grpc.unary_unary_rpc_method_handler(
                    servicer.Retune,
                    request_deserializer=handler__pb2.RetuneRequest.FromString,
                    response_serializer=handler__pb2.HandlerAck.SerializeToString,
            ),
            'OpenChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenChannel,
                    request_deserializer=handler__pb2.OpenChannelRequest.FromString,
                    response_serializer=handler__pb2.OpenChannelResponse.SerializeToString,
            ),
            'CloseChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseChannel,
                    request_deserializer=handler__pb2.CloseChannelRequest.FromString,
                    response_serializer=handler__pb2.HandlerAck.SerializeToString,
            ),
            'AssignTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTask,
                    request_deserializer=handler__pb2.AssignTaskRequest.FromString,
                    response_serializer=handler__pb2.HandlerAck.SerializeToString,
            ),
            'InjectExternalMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectExternalMessage,
                    request_deserializer=handler__pb2.InjectExternalMessageRequest.FromString,
                    response_serializer=handler__pb2.HandlerAck.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=handler__pb2.PauseRequest.FromString,
                    response_serializer=handler__pb2.HandlerAck.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=handler__pb2.ResumeRequest.FromString,
                    response_serializer=handler__pb2.HandlerAck.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=handler__pb2.StepRequest.FromString,
                    response_serializer=handler__pb2.HandlerAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'byzminds.handler.v1.Handler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('byzminds.handler.v1.Handler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Handler(object):
    """Handler is the researcher's privileged control surface. Every RPC:
    1. Authenticates the caller against the kernel-known researcher
    pubkey (per HandlerAuth below).
    2. Commits an event to L_ctrl recording the RPC name + arguments.
    3. Mutates kernel state synchronously (channel mint, agent roster,
    capability table, scheduler pause/step) — wholly within the
    scheduler's tick boundary so replay is bit-deterministic.
    4. Returns an Ack pinning the L_ctrl commit metadata.

    Stage A doesn't exercise every RPC during baseline runs; we wire them
    now so Step 2+ scenarios and Step 3+ steering don't need a retrofit.
    """

    @staticmethod
    def SpawnAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/SpawnAgent',
            handler__pb2.SpawnAgentRequest.SerializeToString,
            handler__pb2.SpawnAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/KillAgent',
            handler__pb2.KillAgentRequest.SerializeToString,
            handler__pb2.HandlerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retune(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/Retune',
            handler__pb2.RetuneRequest.SerializeToString,
            handler__pb2.HandlerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/OpenChannel',
            handler__pb2.OpenChannelRequest.SerializeToString,
            handler__pb2.OpenChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/CloseChannel',
            handler__pb2.CloseChannelRequest.SerializeToString,
            handler__pb2.HandlerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/AssignTask',
            handler__pb2.AssignTaskRequest.SerializeToString,
            handler__pb2.HandlerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectExternalMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/InjectExternalMessage',
            handler__pb2.InjectExternalMessageRequest.SerializeToString,
            handler__pb2.HandlerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/Pause',
            handler__pb2.PauseRequest.SerializeToString,
            handler__pb2.HandlerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/Resume',
            handler__pb2.ResumeRequest.SerializeToString,
            handler__pb2.HandlerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.handler.v1.Handler/Step',
            handler__pb2.StepRequest.SerializeToString,
            handler__pb2.HandlerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
