# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kernel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kernel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from byzminds_agent.proto_gen import events_pb2 as events__pb2
from byzminds_agent.proto_gen import ledger_pb2 as ledger__pb2
from byzminds_agent.proto_gen import view_pb2 as view__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckernel.proto\x12\x12\x62yzminds.kernel.v1\x1a\x0c\x65vents.proto\x1a\x0cledger.proto\x1a\nview.proto\"\xee\x01\n\rCommitReceipt\x12\x11\n\tcommitted\x18\x01 \x01(\x08\x12/\n\tledger_id\x18\x02 \x01(\x0e\x32\x1c.byzminds.ledger.v1.LedgerID\x12\x19\n\x11ledger_channel_id\x18\x03 \x01(\t\x12\x1b\n\x13sequence_per_ledger\x18\x04 \x01(\x04\x12\x19\n\x11global_commit_seq\x18\x05 \x01(\x04\x12\x12\n\nchain_hash\x18\x06 \x01(\x0c\x12\x18\n\x10kernel_signature\x18\x07 \x01(\x0c\x12\x18\n\x10rejection_reason\x18\x08 \x01(\t\"J\n\x0bViewRequest\x12\x15\n\rreader_pubkey\x18\x01 \x01(\x0c\x12\x11\n\tfrom_tick\x18\x02 \x01(\x04\x12\x11\n\tsignature\x18\x03 \x01(\x0c\">\n\tEventView\x12\x31\n\x05\x65vent\x18\x01 \x01(\x0b\x32\".byzminds.ledger.v1.CommittedEvent\"N\n\x10SubscribeRequest\x12\x14\n\x0c\x61gent_pubkey\x18\x01 \x01(\x0c\x12\x11\n\tfrom_tick\x18\x02 \x01(\x04\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x32\xf7\x01\n\x06Kernel\x12S\n\x0bSubmitEvent\x12!.byzminds.events.v1.EventEnvelope\x1a!.byzminds.kernel.v1.CommitReceipt\x12K\n\x07GetView\x12\x1f.byzminds.kernel.v1.ViewRequest\x1a\x1d.byzminds.kernel.v1.EventView0\x01\x12K\n\tSubscribe\x12$.byzminds.kernel.v1.SubscribeRequest\x1a\x16.byzminds.view.v1.View0\x01\x42\x36Z4github.com/byzminds/byzminds/proto/kernelv1;kernelv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kernel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/byzminds/byzminds/proto/kernelv1;kernelv1'
  _globals['_COMMITRECEIPT']._serialized_start=77
  _globals['_COMMITRECEIPT']._serialized_end=315
  _globals['_VIEWREQUEST']._serialized_start=317
  _globals['_VIEWREQUEST']._serialized_end=391
  _globals['_EVENTVIEW']._serialized_start=393
  _globals['_EVENTVIEW']._serialized_end=455
  _globals['_SUBSCRIBEREQUEST']._serialized_start=457
  _globals['_SUBSCRIBEREQUEST']._serialized_end=535
  _globals['_KERNEL']._serialized_start=538
  _globals['_KERNEL']._serialized_end=785
# @@protoc_insertion_point(module_scope)
