# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from byzminds_agent.proto_gen import events_pb2 as events__pb2
from byzminds_agent.proto_gen import kernel_pb2 as kernel__pb2
from byzminds_agent.proto_gen import view_pb2 as view__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kernel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KernelStub(object):
    """Kernel is the gRPC surface of the deterministic core.

    SubmitEvent and GetView are Step 1 surface (committed-event admission +
    researcher snapshot reads). Subscribe is Step 2 surface: a live
    per-tick stream of BuildView outputs for one registered agent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitEvent = channel.unary_unary(
                '/byzminds.kernel.v1.Kernel/SubmitEvent',
                request_serializer=events__pb2.EventEnvelope.SerializeToString,
                response_deserializer=kernel__pb2.CommitReceipt.FromString,
                _registered_method=True)
        self.GetView = channel.unary_stream(
                '/byzminds.kernel.v1.Kernel/GetView',
                request_serializer=kernel__pb2.ViewRequest.SerializeToString,
                response_deserializer=kernel__pb2.EventView.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/byzminds.kernel.v1.Kernel/Subscribe',
                request_serializer=kernel__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=view__pb2.View.FromString,
                _registered_method=True)


class KernelServicer(object):
    """Kernel is the gRPC surface of the deterministic core.

    SubmitEvent and GetView are Step 1 surface (committed-event admission +
    researcher snapshot reads). Subscribe is Step 2 surface: a live
    per-tick stream of BuildView outputs for one registered agent.
    """

    def SubmitEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEvent,
                    request_deserializer=events__pb2.EventEnvelope.FromString,
                    response_serializer=kernel__pb2.CommitReceipt.SerializeToString,
            ),
            'GetView': grpc.unary_stream_rpc_method_handler(
                    servicer.GetView,
                    request_deserializer=kernel__pb2.ViewRequest.FromString,
                    response_serializer=kernel__pb2.EventView.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=kernel__pb2.SubscribeRequest.FromString,
                    response_serializer=view__pb2.View.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'byzminds.kernel.v1.Kernel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('byzminds.kernel.v1.Kernel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kernel(object):
    """Kernel is the gRPC surface of the deterministic core.

    SubmitEvent and GetView are Step 1 surface (committed-event admission +
    researcher snapshot reads). Subscribe is Step 2 surface: a live
    per-tick stream of BuildView outputs for one registered agent.
    """

    @staticmethod
    def SubmitEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzminds.kernel.v1.Kernel/SubmitEvent',
            events__pb2.EventEnvelope.SerializeToString,
            kernel__pb2.CommitReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/byzminds.kernel.v1.Kernel/GetView',
            kernel__pb2.ViewRequest.SerializeToString,
            kernel__pb2.EventView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/byzminds.kernel.v1.Kernel/Subscribe',
            kernel__pb2.SubscribeRequest.SerializeToString,
            view__pb2.View.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
