# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ledger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ledger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from byzminds_agent.proto_gen import events_pb2 as events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cledger.proto\x12\x12\x62yzminds.ledger.v1\x1a\x0c\x65vents.proto\"\x8e\x02\n\x0e\x43ommittedEvent\x12\x33\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32!.byzminds.events.v1.EventEnvelope\x12/\n\tledger_id\x18\x02 \x01(\x0e\x32\x1c.byzminds.ledger.v1.LedgerID\x12\x19\n\x11ledger_channel_id\x18\x03 \x01(\t\x12\x19\n\x11global_commit_seq\x18\x04 \x01(\x04\x12\x19\n\x11\x63ommit_unix_nanos\x18\x05 \x01(\x04\x12\x17\n\x0fprev_chain_hash\x18\x06 \x01(\x0c\x12\x12\n\nchain_hash\x18\x07 \x01(\x0c\x12\x18\n\x10kernel_signature\x18\x08 \x01(\x0c\"\xc1\x01\n\nChainInput\x12\x33\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32!.byzminds.events.v1.EventEnvelope\x12/\n\tledger_id\x18\x02 \x01(\x0e\x32\x1c.byzminds.ledger.v1.LedgerID\x12\x19\n\x11ledger_channel_id\x18\x03 \x01(\t\x12\x19\n\x11global_commit_seq\x18\x04 \x01(\x04\x12\x17\n\x0fprev_chain_hash\x18\x05 \x01(\x0c*\x97\x01\n\x08LedgerID\x12\x19\n\x15LEDGER_ID_UNSPECIFIED\x10\x00\x12\x13\n\x0fLEDGER_ID_L_PUB\x10\x01\x12\x13\n\x0fLEDGER_ID_L_PRV\x10\x02\x12\x17\n\x13LEDGER_ID_L_COG_IND\x10\x03\x12\x17\n\x13LEDGER_ID_L_COG_ELI\x10\x04\x12\x14\n\x10LEDGER_ID_L_CTRL\x10\x05\x42\x36Z4github.com/byzminds/byzminds/proto/ledgerv1;ledgerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ledger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/byzminds/byzminds/proto/ledgerv1;ledgerv1'
  _globals['_LEDGERID']._serialized_start=520
  _globals['_LEDGERID']._serialized_end=671
  _globals['_COMMITTEDEVENT']._serialized_start=51
  _globals['_COMMITTEDEVENT']._serialized_end=321
  _globals['_CHAININPUT']._serialized_start=324
  _globals['_CHAININPUT']._serialized_end=517
# @@protoc_insertion_point(module_scope)
