# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: view.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'view.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from byzminds_agent.proto_gen import events_pb2 as events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nview.proto\x12\x10\x62yzminds.view.v1\x1a\x0c\x65vents.proto\"\xac\x03\n\x04View\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0c\n\x04tick\x18\x02 \x01(\x04\x12\x1b\n\x13\x63hannel_memberships\x18\x03 \x03(\t\x12\x1b\n\x13loaded_capabilities\x18\x04 \x03(\t\x12/\n\x08scenario\x18\x05 \x01(\x0b\x32\x1d.byzminds.view.v1.ScenarioRef\x12\x15\n\rtask_artifact\x18\x06 \x01(\t\x12\r\n\x05phase\x18\x07 \x01(\t\x12\r\n\x05round\x18\x08 \x01(\r\x12\x14\n\x0ctotal_rounds\x18\t \x01(\r\x12;\n\x11\x63hannel_histories\x18\n \x03(\x0b\x32 .byzminds.view.v1.ChannelHistory\x12\x38\n\x11\x65xternal_messages\x18\x0b \x03(\x0b\x32\x1d.byzminds.view.v1.ExternalMsg\x12\x17\n\x0f\x61vailable_tools\x18\x0c \x03(\t\x12>\n\x0e\x65licit_request\x18\r \x01(\x0b\x32&.byzminds.events.v1.ElicitationRequest\"@\n\x0bScenarioRef\x12\x15\n\rscenario_name\x18\x01 \x01(\t\x12\x1a\n\x12scenario_yaml_hash\x18\x02 \x01(\t\"Q\n\x0e\x43hannelHistory\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12+\n\x08messages\x18\x02 \x03(\x0b\x32\x19.byzminds.view.v1.Message\"V\n\x07Message\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04tick\x18\x03 \x01(\x04\x12\x19\n\x11global_commit_seq\x18\x04 \x01(\x04\"K\n\x0b\x45xternalMsg\x12\x16\n\x0e\x63laimed_source\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x13\n\x0binject_tick\x18\x03 \x01(\x04\x42\x32Z0github.com/byzminds/byzminds/proto/viewv1;viewv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'view_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/byzminds/byzminds/proto/viewv1;viewv1'
  _globals['_VIEW']._serialized_start=47
  _globals['_VIEW']._serialized_end=475
  _globals['_SCENARIOREF']._serialized_start=477
  _globals['_SCENARIOREF']._serialized_end=541
  _globals['_CHANNELHISTORY']._serialized_start=543
  _globals['_CHANNELHISTORY']._serialized_end=624
  _globals['_MESSAGE']._serialized_start=626
  _globals['_MESSAGE']._serialized_end=712
  _globals['_EXTERNALMSG']._serialized_start=714
  _globals['_EXTERNALMSG']._serialized_end=789
# @@protoc_insertion_point(module_scope)
